Merging in DevOps Insight from jparra5

diff --git a/.bluemix/catalog-api.pipeline.yml b/.bluemix/catalog-api.pipeline.yml
--- a/.bluemix/catalog-api.pipeline.yml
+++ b/.bluemix/catalog-api.pipeline.yml
@@ -7,12 +7,29 @@ stages:
     service: ${CATALOG_API_REPO}
   triggers:
   - type: commit
+  properties:
+  - name: LOGICAL_APP_NAME
+    value: ${CF_APP_NAME}
+    type: text
+  - name: LOGICAL_ENV_NAME
+    value: master
+    type: text
+  - name: BUILD_PREFIX
+    value: master
+    type: text
   jobs:
   - name: Build
     type: builder
   - name: Unit Tests
     type: tester
-    script: |-
+    extension_id: ibm.devops.services.pipeline.dra_upload_results
+    APPLICATION_NAME: ${CF_APP_NAME}
+    ENVIRONMENT: master
+    LIFE_CYCLE_STAGE_SELECT: unittest
+    ADDITIONAL_LIFE_CYCLE_STAGE_SELECT: code
+    LOG_FILE: tests/server/mochatest.json
+    ADDITIONAL_LOG_FILE: tests/server/coverage/reports/coverage-summary.json
+    COMMAND: |-
       #!/bin/bash
       GRUNTFILE="tests/Gruntfile.js"
       if [ -f $GRUNTFILE ]; then
@@ -21,7 +38,13 @@ stages:
         grunt dev-test-cov --no-color -f --gruntfile $GRUNTFILE --base .
       else
         echo "$GRUNTFILE not found."
-      fi      
+      fi
+  - name: Gate
+    type: tester
+    extension_id: ibm.devops.services.pipeline.dra_devops_gate
+    CRITERIA: Store Unit Test and Code Coverage Checks
+    APPLICATION_NAME: ${CF_APP_NAME}
+    ENVIRONMENT: master
 - name: DEV
   inputs:
   - type: job
@@ -35,6 +58,15 @@ stages:
     type: text
   - name: APP_URL
     value: undefined
+    type: text
+  - name: LOGICAL_APP_NAME
+    value: ${CF_APP_NAME}
+    type: text
+  - name: LOGICAL_ENV_NAME
+    value: ${DEV_SPACE_NAME}
+    type: text
+  - name: BUILD_PREFIX
+    value: master
     type: text
   jobs:
   - name: Deploy
@@ -55,7 +87,13 @@ stages:
       #cf logs "${CF_APP_NAME}" --recent
   - name: Functional Tests
     type: tester
-    script: |-
+    extension_id: ibm.devops.services.pipeline.dra_upload_results
+    APPLICATION_NAME: ${CF_APP_NAME}
+    ENVIRONMENT: ${DEV_SPACE_NAME}
+    LIFE_CYCLE_STAGE_SELECT: fvt
+    ADDITIONAL_LIFE_CYCLE_STAGE_SELECT: none
+    LOG_FILE: tests/fvt/mochafvttest.json
+    COMMAND: |-
       #!/bin/bash
       export CATALOG_API_TEST_SERVER=$APP_URL
       GRUNTFILE="tests/Gruntfile.js"
@@ -79,6 +117,27 @@ stages:
     type: text
   - name: APP_URL
     value: undefined
+    type: text
+  - name: SAUCE_USERNAME
+    value: {{test.parameters.username}}
+    type: text
+  - name: SAUCE_ACCESS_KEY
+    value: {{test.parameters.key}}
+    type: text
+  - name: LOGICAL_APP_NAME
+    value: ${CF_APP_NAME}
+    type: text
+  - name: LOGICAL_ENV_NAME
+    value: ${QA_SPACE_NAME}
+    type: text
+  - name: BUILD_PREFIX
+    value: master
+    type: text
+  - name: HOST
+    value: ondemand.saucelabs.com
+    type: text
+  - name: PORT
+    value: '80'
     type: text
   jobs:
   - name: Deploy
@@ -120,9 +179,31 @@ stages:
         fi
       else
         echo "$GRUNTFILE not found."
-      fi      
+      fi
     enable_tests: true
     test_file_pattern: '*.xml'
+  - name: Functional Tests
+    type: tester
+    extension_id: ibm.devops.services.pipeline.dra_upload_results
+    APPLICATION_NAME: ${CF_APP_NAME}
+    LIFE_CYCLE_STAGE_SELECT: fvt
+    ADDITIONAL_LIFE_CYCLE_STAGE_SELECT: none
+    LOG_FILE: xunit.xml
+    COMMAND: |-
+      #!/bin/bash
+      GRUNTFILE="tests/Gruntfile.js"
+      if [ -f $GRUNTFILE ]; then
+        npm install
+        echo $APP_URL | grep "stage1"
+        if [ $? -eq 0 ]; then
+          grunt test_fake -f --gruntfile $GRUNTFILE --base .
+        else
+          grunt test_real -f --gruntfile $GRUNTFILE --base .
+        fi
+      else
+        echo "$GRUNTFILE not found."
+      fi
+    ENVIRONMENT: ${QA_SPACE_NAME}
 - name: PROD
   inputs:
   - type: job
@@ -133,6 +214,15 @@ stages:
   properties:
   - name: CF_APP_NAME
     value: undefined
+    type: text
+  - name: LOGICAL_APP_NAME
+    value: ${CF_APP_NAME}
+    type: text
+  - name: LOGICAL_ENV_NAME
+    value: ${PROD_SPACE_NAME}
+    type: text
+  - name: BUILD_PREFIX
+    value: master
     type: text
   jobs:
   - name: Blue/Green Deploy
diff --git a/.bluemix/order-api.pipeline.yml b/.bluemix/order-api.pipeline.yml
--- a/.bluemix/order-api.pipeline.yml
+++ b/.bluemix/order-api.pipeline.yml
@@ -7,6 +7,16 @@ stages:
     service: ${ORDER_API_REPO}
   triggers:
   - type: commit
+  properties:
+  - name: LOGICAL_APP_NAME
+    value: ${CF_APP_NAME}
+    type: text
+  - name: BUILD_PREFIX
+    value: master
+    type: text
+  - name: LOGICAL_ENV_NAME
+    value: master
+    type: text
   jobs:
   - name: Build
     type: builder
@@ -24,6 +34,15 @@ stages:
     type: text
   - name: APP_URL
     value: undefined
+    type: text
+  - name: LOGICAL_ENV_NAME
+    value: ${DEV_SPACE_NAME}
+    type: text
+  - name: LOGICAL_APP_NAME
+    value: ${CF_APP_NAME}
+    type: text
+  - name: BUILD_PREFIX
+    value: master
     type: text
   jobs:
   - name: Deploy
@@ -54,6 +73,27 @@ stages:
     type: text
   - name: APP_URL
     value: undefined
+    type: text
+  - name: SAUCE_USERNAME
+    value: {{test.parameters.username}}
+    type: text
+  - name: SAUCE_ACCESS_KEY
+    value: {{test.parameters.key}}
+    type: text
+  - name: HOST
+    value: ondemand.saucelabs.com
+    type: text
+  - name: PORT
+    value: '80'
+    type: text
+  - name: LOGICAL_APP_NAME
+    value: ${CF_APP_NAME}
+    type: text
+  - name: BUILD_PREFIX
+    value: master
+    type: text
+  - name: LOGICAL_ENV_NAME
+    value: ${QA_SPACE_NAME}
     type: text
   jobs:
   - name: Deploy
@@ -98,6 +138,28 @@ stages:
       fi
     enable_tests: true
     test_file_pattern: '*.xml'
+  - name: Functional Tests
+    type: tester
+    extension_id: ibm.devops.services.pipeline.dra_upload_results
+    APPLICATION_NAME: ${CF_APP_NAME}
+    LIFE_CYCLE_STAGE_SELECT: fvt
+    ADDITIONAL_LIFE_CYCLE_STAGE_SELECT: none
+    LOG_FILE: ./xunit.xml
+    COMMAND: |-
+      #!/bin/bash
+      GRUNTFILE="tests/Gruntfile.js"
+      if [ -f $GRUNTFILE ]; then
+        npm install
+        echo $APP_URL | grep "stage1"
+        if [ $? -eq 0 ]; then
+          grunt test_fake -f --gruntfile $GRUNTFILE --base .
+        else
+          grunt test_real -f --gruntfile $GRUNTFILE --base .
+        fi
+      else
+        echo "$GRUNTFILE not found."
+      fi
+    ENVIRONMENT: ${QA_SPACE_NAME}
 - name: PROD
   inputs:
   - type: job
@@ -112,6 +174,15 @@ stages:
   - name: APP_URL
     value: undefined
     type: text
+  - name: BUILD_PREFIX
+    value: master
+    type: text
+  - name: LOGICAL_APP_NAME
+    value: ${CF_APP_NAME}
+    type: text
+  - name: LOGICAL_ENV_NAME
+    value: ${PROD_SPACE_NAME}
+    type: text
   jobs:
   - name: Blue/Green Deploy
     type: deployer
@@ -123,12 +194,12 @@ stages:
     script: |-
       #!/bin/bash
       cf create-service cloudantNoSQLDB Lite myMicroservicesCloudant
-      if ! cf app $CF_APP; then  
+      if ! cf app $CF_APP; then
         cf push $CF_APP
       else
         OLD_CF_APP=${CF_APP}-OLD-$(date +"%s")
         rollback() {
-          set +e  
+          set +e
           if cf app $OLD_CF_APP; then
             cf logs $CF_APP --recent
             cf delete $CF_APP -f
